// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Server.Data;

#nullable disable

namespace Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("CounterServiceType", b =>
                {
                    b.Property<int>("CountersCounterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SupportedServicesServiceTypeId")
                        .HasColumnType("INTEGER");

                    b.HasKey("CountersCounterId", "SupportedServicesServiceTypeId");

                    b.HasIndex("SupportedServicesServiceTypeId");

                    b.ToTable("CounterServiceType");
                });

            modelBuilder.Entity("Shared.Models.Branch", b =>
                {
                    b.Property<int>("BranchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .HasColumnType("TEXT");

                    b.HasKey("BranchId");

                    b.ToTable("Branches");
                });

            modelBuilder.Entity("Shared.Models.Counter", b =>
                {
                    b.Property<int>("CounterId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsBusy")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CounterId");

                    b.HasIndex("BranchId");

                    b.ToTable("Counters");
                });

            modelBuilder.Entity("Shared.Models.ServiceType", b =>
                {
                    b.Property<int>("ServiceTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasColumnType("TEXT");

                    b.Property<int>("EstimatedMinutes")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Prefix")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.HasKey("ServiceTypeId");

                    b.ToTable("ServiceTypes");
                });

            modelBuilder.Entity("Shared.Models.Ticket", b =>
                {
                    b.Property<int>("TicketId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int?>("AssignedCounterId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BranchId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("CalledAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("CancelComment")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("Number")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Result")
                        .HasColumnType("TEXT");

                    b.Property<int>("ServiceTypeId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SkipComment")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("TicketId");

                    b.HasIndex("AssignedCounterId");

                    b.HasIndex("CreatedAt");

                    b.HasIndex("ServiceTypeId");

                    b.HasIndex("BranchId", "ServiceTypeId");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("CounterServiceType", b =>
                {
                    b.HasOne("Shared.Models.Counter", null)
                        .WithMany()
                        .HasForeignKey("CountersCounterId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Shared.Models.ServiceType", null)
                        .WithMany()
                        .HasForeignKey("SupportedServicesServiceTypeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Shared.Models.Counter", b =>
                {
                    b.HasOne("Shared.Models.Branch", "Branch")
                        .WithMany("Counters")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Branch");
                });

            modelBuilder.Entity("Shared.Models.Ticket", b =>
                {
                    b.HasOne("Shared.Models.Counter", "AssignedCounter")
                        .WithMany("Tickets")
                        .HasForeignKey("AssignedCounterId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Shared.Models.Branch", "Branch")
                        .WithMany("Tickets")
                        .HasForeignKey("BranchId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Shared.Models.ServiceType", "ServiceType")
                        .WithMany("Tickets")
                        .HasForeignKey("ServiceTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("AssignedCounter");

                    b.Navigation("Branch");

                    b.Navigation("ServiceType");
                });

            modelBuilder.Entity("Shared.Models.Branch", b =>
                {
                    b.Navigation("Counters");

                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Shared.Models.Counter", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("Shared.Models.ServiceType", b =>
                {
                    b.Navigation("Tickets");
                });
#pragma warning restore 612, 618
        }
    }
}
